# Generated by Django 5.0.14 on 2026-09-30 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.classsection'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.school'),
        ),
        migrations.AddField(
            model_name='classsection',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.schoolclass'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentattendancerecord',
            name='daily_attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='academics.dailyattendance'),
        ),
        migrations.AddField(
            model_name='studentattendancerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academics.student'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.classsection'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.student'),
        ),
        migrations.AddField(
            model_name='studentleave',
            name='action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentleave',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='academics.student'),
        ),
        migrations.AddField(
            model_name='targetednotice',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
        migrations.AddField(
            model_name='targetednotice',
            name='target_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.schoolclass'),
        ),
        migrations.AddField(
            model_name='targetednotice',
            name='target_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.classsection'),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dailyattendance',
            unique_together={('section', 'attendance_date')},
        ),
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='classsection',
            unique_together={('school_class', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('school', 'admission_number'), ('school', 'student_id_code')},
        ),
        migrations.AlterUniqueTogether(
            name='studentattendancerecord',
            unique_together={('daily_attendance', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together={('student', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherattendance',
            unique_together={('teacher', 'date')},
        ),
    ]
